name: medusa
description: "Medusa - Women's Safety App"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  
  shared_preferences: ^2.5.4
  sqflite: ^2.3.3
  flutter_secure_storage: ^9.0.0
  
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^6.0.0
  flutter_foreground_task: ^8.11.0
  
  sensors_plus: ^5.0.1
  battery_plus: ^6.0.1
  
  record: ^6.0.0
  audioplayers: ^6.0.0
  
  camera: ^0.11.0+2
  
  pdf: ^3.10.8
  printing: ^5.12.0
  
  flutter_local_notifications: ^17.2.2
  torch_light: ^1.1.0
  
  flutter_tts: ^4.0.2
  url_launcher: ^6.3.0
  
  local_auth: ^2.2.0
  
  flutter_blue_plus: ^1.32.12
  path_provider: ^2.1.3
  
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  speech_to_text: ^7.0.0
  supabase_flutter: ^2.12.0
  uuid: ^4.5.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  
  # Uncomment when you add actual assets
  assets:
    - assets/images/medusa.jpg
